# LG_BTUI : 0019632 chanha.park@lge.com 2012-05-31
# BRCM bluetooth enabled : board-d1l-rfkill.o
obj-$(CONFIG_MACH_MSM8960_D1L_KR) += board-d1l.o \
	board-d1l-regulator.o \
	board-d1l-pm.o \
	board-d1l-input.o \
	board-d1l-misc.o \
	board-d1l-panel.o \
	board-d1l-camera.o \
	board-d1l-gpiomux.o \
	board-d1l-mmc.o \
	board-d1l-usb.o \
	board-d1l-sound.o \
	board-d1l-nfc.o \
	board-d1l-rfkill.o
