/*
 * This software is contributed or developed by KYOCERA Corporation.
 * (C) 2012 KYOCERA Corporation
*/
#ifndef CUSTMCAM_H
#define CUSTMCAM_H

#define FEATURE_KYOCERA_MCAM

#define FEATURE_KYOCERA_MCAM_BB_ADJ
#undef FEATURE_KYOCERA_MCAM_BB_ADJ

#define FEATURE_KYOCERA_MCAM_DATALINE_CHECK
#undef FEATURE_KYOCERA_MCAM_DATALINE_CHECK

#undef FEATURE_KYOCERA_DLCHK_GRADATION_PATTERN
#define FEATURE_KYOCERA_DLCHK_UVFIX_PATTERN

#endif

