obj-$(CONFIG_MACH_MSM8960_D1L) += board-d1l.o \
	board-d1l-regulator.o \
	board-d1l-pm.o \
	board-d1l-input.o \
	board-d1l-misc.o \
	board-d1l-panel.o \
	board-d1l-camera.o \
	board-d1l-gpiomux.o \
	board-d1l-mmc.o \
	board-d1l-usb.o \
	board-d1l-sound.o \
	board-d1l-nfc.o
