obj-$(CONFIG_MACH_MSM8960_LX) += board-lx.o \
	board-lx-regulator.o \
	board-lx-pm.o \
	board-lx-input.o \
	board-lx-misc.o \
	board-lx-panel.o \
	board-lx-camera.o \
	board-lx-gpiomux.o \
	board-lx-mmc.o \
	board-lx-usb.o \
	board-lx-sound.o \
	board-lx-nfc.o
